# Generated by Django 5.2.5 on 2026-02-20 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMonthStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, help_text='If False, member is fully off for this month')),
                ('active_from', models.DateField(blank=True, help_text='If set, member is only active from this date onwards (within the month)', null=True)),
                ('active_until', models.DateField(blank=True, help_text='If set, member is only active until this date (within the month)', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_month_statuses', to='flats.flat')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_statuses', to='flats.flatmembership')),
            ],
            options={
                'db_table': 'member_month_status',
                'indexes': [models.Index(fields=['flat', 'year', 'month'], name='member_mont_flat_id_2a865e_idx')],
                'unique_together': {('membership', 'year', 'month')},
            },
        ),
    ]
