# Generated by Django 6.0.1 on 2026-03-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_membermonthstatus'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='granted_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions to assign to members who join via this invite.', related_name='invite_tokens', to='permissions.apppermission'),
        ),
    ]
