# Generated by Django 5.2.5 on 2026-02-20 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0002_membermonthstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Logged in'), ('logout', 'Logged out'), ('register', 'Registered'), ('meal_add', 'Added meal entry'), ('meal_update', 'Updated meal entry'), ('month_lock', 'Locked month'), ('month_unlock', 'Unlocked month'), ('expense_add', 'Added expense'), ('expense_update', 'Updated expense'), ('expense_delete', 'Deleted expense'), ('member_invite', 'Created invite link'), ('member_join', 'Joined flat'), ('member_remove', 'Removed member'), ('member_status', 'Updated member month status'), ('permission_update', 'Updated permissions'), ('flat_update', 'Updated flat details')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='flats.flat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'), models.Index(fields=['flat', '-created_at'], name='activity_lo_flat_id_1db4e2_idx'), models.Index(fields=['action', '-created_at'], name='activity_lo_action_78df1b_idx')],
            },
        ),
    ]
