# Generated by Django 5.2.5 on 2026-02-20 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('meal_count', models.DecimalField(decimal_places=1, default=0, help_text='Supports half meals: 0, 0.5, 1, 1.5, 2, 3…', max_digits=4)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='flats.flat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_entries',
                'indexes': [models.Index(fields=['flat', 'date'], name='meal_entrie_flat_id_8854af_idx'), models.Index(fields=['flat', 'user', 'date'], name='meal_entrie_flat_id_3f6ea0_idx')],
                'unique_together': {('flat', 'user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_meals', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meal_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_locked', models.BooleanField(default=False, help_text='Month-lock flag')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='flats.flat')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monthly_summaries',
                'indexes': [models.Index(fields=['flat', 'year', 'month'], name='monthly_sum_flat_id_574402_idx')],
                'unique_together': {('flat', 'year', 'month')},
            },
        ),
    ]
