# Generated by Django 5.2.5 on 2026-02-20 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(db_index=True, max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('module', models.CharField(db_index=True, help_text='Logical module: meals, expenses, analytics, members, flat', max_length=30)),
            ],
            options={
                'db_table': 'app_permissions',
                'ordering': ['module', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='MemberPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='flats.flatmembership')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='permissions.apppermission')),
            ],
            options={
                'db_table': 'member_permissions',
                'indexes': [models.Index(fields=['membership', 'permission'], name='member_perm_members_05b8d0_idx')],
                'unique_together': {('membership', 'permission')},
            },
        ),
    ]
